/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/status": {
    /** @description get status */
    get: operations["status"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description error description */
    Error: {
      message: string;
    };
    /** @description Status */
    Status: {
      /**
       * @description Status 
       * @enum {string}
       */
      status: "ok" | "error";
      /** @description Message */
      message?: string;
    };
  };
  responses: {
    /** @description Error while processing request */
    Error: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** @description get status */
  status: {
    responses: {
      /** @description Coordinator status */
      200: {
        content: {
          "application/json": components["schemas"]["Status"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
}
